### PR TITLE
add for_loop.ipynb, while_loop.ipynb

### PR DESCRIPTION
**Pull request by jeelion22**
The below files are added in the week_2 directory
1. for_loop.ipynb
2. while_loop.ipynb

### CODE REVIEW

**Review by josef-o — APPROVED** [review]
# `for_loop.ipynb`

### Exercise 3

Here you print all the key-values of the dictionaries but I understood the question as only printing a preset key for all the dicts.

### Opinion corner

In this one you use many intermediate variables (i.e. `upper_case`, `num_sqr`, `sum_item`) which can be a good idea for better readability, but I would argue it works when the expressions they substitute are more complex or the names given to the variables are more descriptive than in this case.

Either way it doesn't matter much, everything is fine as is :+1: 

# `while_loop.ipynb`

Everything is ok as is, I mostly have style suggestions (which are nothing more than a matter of opinion).

### Exercises 1 and 3

I would remove the `continue` and use the `else` block for the `break`, moving the `print` outside of the `while` loop. 

That way the loop logic is clearer and the result (the `print`) happens after the computation, instead of inside.

### Exercise 4

The `continue` is not needed.

### Exercise 5

The `highest` variable is being kept as a string which can lead to confusion.
Casting it to `float` in the assignment would make the `if` condition shorter without the `float(highest)' which is a bit counter intuitive to read at first.

Again I believe it looks cleaner if the final `print` comes after the loop... but it is also completely fine like this.

**Comment by rzmobiledev** [comment]
on while loop.
1. Create a while loop that repeatedly takes user input and adds the input to a list until the user enters "done".

here is my proposal :

`inp_lst = []

while True :
    inp = input("Enter something until you enter 'done': ")
    if inp == "done":
        break
  
    inp_lst.append(inp)

print(inp_lst)`

**Review by rzmobiledev — APPROVED** [review]

**Comment by jeelion22** [comment]
Guys, I have made some changes according to your review. Thanks for pointing them out, and when I look back into my code, yes, I felt the same as you.

Done:
In for_loop.ipynb file:
       3. The code is changed for the specific key to print.

In while_loop.ipynb file:
       Probs.1, 2, 3, 4, and 5  logics are simplified, in additional "A BUG" in 4 is captured; when entering 10, the script should come to end but previously it was not."

**Comment by josef-o** [comment]
In Exercise 5 of `while_loop.ipynb` the condition in the `if` clause is now way more confusing and like in the last assignment it doesn't accept `0` as a valid input.

**Comment by jeelion22** [comment]
Okay, it check that now.

**Comment by jeelion22** [comment]
I hope now,  it will be understood. The bug is fixed.

**Comment by josef-o** [comment]
> I hope now, it will be understood. The bug is fixed.

Yep, much better now :+1:

**Review by josef-o — APPROVED** [review]
## Exercise 1

The try-except block isn't needed here, it is not user facing and you aren't handling the exceptions just returning `None`. 

Still, you can leave it as is if you'd like.

## Exercise 2

Same as above.

Also beware that in the case `max_val < 1` you are returning a string instead of printing a warning or raising a `ValueError`, not really advisable.

## Exercise 3

Here you switched the function name to camelCase, it's not wrong but the python convention is snake_case (as you were using before).

## Exercise 4

Doesn't need to be a function in the first place, it would make sense if it had any parameters but it doesn't.

## Exercise 5

Again camelCase.

It is good that you add comments here. The comment at the top maybe you can remove it and add a docstring to the function instead.

## Exercise 6

You used the Gauss formulas, that's cool.

## Exercise 7

Again camelCase and good place for docstrings.

You are returning the error message (also f-string not used).

The primality check function is checking two factors at a time and skipping multiples of 3 and 2, right? That's just to speed it up or is there something I'm not understanding?

## Exercise 8

Here you wrote a docstring but not its function...

## Exercise 9

Same as 7.

## Exercise 10

Making the comment a docstring wouldn't hurt.

You were respecting the python convention of spaces between operands (thumbs up for that) here you missed the last `n*(n+1)`.

Cool solution.

**Comment by jeelion22** [comment]
"Thank you for your detailed review! Your feedback has helped me be more strict with the intended problems, avoid using unnecessary exception handling, and see the importance of adding docstrings and comments to my code. Your appreciation means a lot to me and strengthens my motivation. I have made the suggested changes and committed the updated project_euler_01.ipynb file for your review. Thank you again for your help!"

**Comment by josef-o** [comment]
Ok please remember that my feedback is just suggestions, don't take them too seriously.

On that note let me clarify that docstrings are strings placed just below function declarations or at the top of modules to document what they do. 
The first line is meant to be a short explanation and details and other notes are meant to be put in separate paragraphs (ides and code completion tools use the first line as a short description and show the rest when a detailed view is requested).

You don't need to preface them with "This function returns..." just start them with "Returns..."

Also docstrings aren't just triple-quoted strings, it's where they are that make them docstrings.

About that, triple-quoted strings aren't strictly speaking multi line comments even though they can be used as such (the python interpreter just ignores them as expressions that don't do anything) and it's better to use actual comments `#` in the final code.

You removed some of the functions which were actually parametrized and it was good that they were like that. I was only suggesting you remove the function `largest_palindrome_product` because it didn't make much sense to have it, but the other ones did.

**Comment by jeelion22** [comment]
I got your points, a new commit is there

**Pull request merged**
